
server:
  applicationContextPath: /ods/userservice/api

couchDb:
  url: http://localhost:5984/
  dbPrefix: ods
  maxConnections: 100
  admin:
    username: admin
    password: admin

auth:
  users:
    - name: Admin
      email: admin@adminland.com
      role: ADMIN
      password: admin123
      type: basic
  googleOAuthWebClientId: 385639345148-tlai63t7bh4fnpr33fo8h3ptotquo68s.apps.googleusercontent.com
  googleOAuthClientIds:
    - 385639345148-aiqgvp9r1vvm6ll9ojib69ns60m39til.apps.googleusercontent.com
