#!/bin/bash

set -u
set -e
set -x

CONFIG_FILE="userservice-configuration.yml"
DEFAULT_COUCHDB_ODSADMIN_PASSWORD="admin"
DEFAULT_COUCHDB_URL="http://localhost:5994/"
DEFAULT_COUCHDB_MAX_CONNECTIONS="100"
DEFAULT_ODS_ADMIN_CONTEXT_PATH="/"
DEFAULT_ODS_CONTEXT_PATH=""
DEFAULT_ODS_ADMIN_PASSWORD="admin"
DEFAULT_NO_VALUE="no-value"
DEFAULT_MESSAGE_BROKER_HOST="localhost"
DEFAULT_MESSAGE_BROKER_VHOST="/"
DEFAULT_MESSAGE_BROKER_PORT="5672"
DEFAULT_MESSAGE_BROKER_MANAGEMENT_PORT="15672"
DEFAULT_MESSAGE_BROKER_USERNAME="guest"
DEFAULT_MESSAGE_BROKER_PASSWORD="guest"

if [[ ! -f finished-ods-config ]]; then

	mkdir -p $ODS_LOG_DIR

	if [[ -f $CONFIG_FILE ]]; then
		sed -ie "s/COUCHDB_ODSADMIN_PASSWORD/${COUCHDB_ODSADMIN_PASSWORD:-$DEFAULT_COUCHDB_ODSADMIN_PASSWORD}/" $CONFIG_FILE
		sed -ie "s|COUCHDB_URL|${COUCHDB_URL:-$DEFAULT_COUCHDB_URL}|" $CONFIG_FILE
		sed -ie "s|COUCHDB_MAX_CONNECTIONS|${COUCHDB_MAX_CONNECTIONS:-$DEFAULT_COUCHDB_MAX_CONNECTIONS}|" $CONFIG_FILE
		sed -ie "s|ODS_ADMIN_CONTEXT_PATH|${ODS_ADMIN_CONTEXT_PATH:-$DEFAULT_ODS_ADMIN_CONTEXT_PATH}|" $CONFIG_FILE
		sed -ie "s|ODS_CONTEXT_PATH|${ODS_CONTEXT_PATH:-$DEFAULT_ODS_CONTEXT_PATH}|" $CONFIG_FILE
		sed -ie "s|ODS_ADMIN_PASSWORD|${ODS_ADMIN_PASSWORD:-$DEFAULT_ODS_ADMIN_PASSWORD}|" $CONFIG_FILE
		sed -ie "s/GOOGLE_OAUTH_WEB_CLIENT_ID/${GOOGLE_OAUTH_WEB_CLIENT_ID:-$DEFAULT_NO_VALUE}/" $CONFIG_FILE
		sed -ie "s/GOOGLE_OAUTH_CLIENT_ID_1/${GOOGLE_OAUTH_CLIENT_ID_1:-$DEFAULT_NO_VALUE}/" $CONFIG_FILE
		sed -ie "s/GOOGLE_OAUTH_CLIENT_ID_2/${GOOGLE_OAUTH_CLIENT_ID_2:-$DEFAULT_NO_VALUE}/" $CONFIG_FILE
		sed -ie "s|MESSAGE_BROKER_HOST|${MESSAGE_BROKER_HOST:-DEFAULT_MESSAGE_BROKER_HOST}|" $CONFIG_FILE
		sed -ie "s|MESSAGE_BROKER_VHOST|${MESSAGE_BROKER_VHOST:-DEFAULT_MESSAGE_BROKER_VHOST}|" $CONFIG_FILE
		sed -ie "s|MESSAGE_BROKER_PORT|${MESSAGE_BROKER_PORT:-DEFAULT_MESSAGE_BROKER_PORT}|" $CONFIG_FILE
		sed -ie "s|MESSAGE_BROKER_MANAGEMENT_PORT|${MESSAGE_BROKER_MANAGEMENT_PORT:-DEFAULT_MESSAGE_BROKER_MANAGEMENT_PORT}|" $CONFIG_FILE
		sed -ie "s|MESSAGE_BROKER_USERNAME|${MESSAGE_BROKER_USERNAME:-DEFAULT_MESSAGE_BROKER_USERNAME}|" $CONFIG_FILE
		sed -ie "s|MESSAGE_BROKER_PASSWORD|${MESSAGE_BROKER_PASSWORD:-DEFAULT_MESSAGE_BROKER_PASSWORD}|" $CONFIG_FILE
	fi
	cat $CONFIG_FILE

	touch finished-userservice-config
fi
